import { useEffect, useState, type FormEvent } from "react";
import type { ApiClient, Plantilla, Registro } from "@flowsort/shared";
import { DynamicFields } from "../components/DynamicFields";
import { QuickInsights, StatsStrip } from "../components/StatsStrip";

export function Registros({ api, monitoreo = false }: { api: ApiClient; monitoreo?: boolean }) {
  const [items, setItems] = useState<(Registro & { plantilla: Plantilla })[]>([]);
  const [plantillas, setPlantillas] = useState<Plantilla[]>([]);
  const [nuevo, setNuevo] = useState(false), [paso, setPaso] = useState(1), [base, setBase] = useState<Record<string, string>>({});
  const [campos, setCampos] = useState<Record<string, unknown>>({}), [buscar, setBuscar] = useState("");
  const [plantillaId, setPlantillaId] = useState("");
  async function cargar() { const p = await api.request<Plantilla[]>("/plantillas?soloDefault=true"); setPlantillas(p); setPlantillaId(x => x || p[0]?.id || ""); const r = await api.request<any>(`${monitoreo ? "/monitoreo/registros" : "/registros"}?busqueda=${encodeURIComponent(buscar)}`); setItems(Array.isArray(r) ? r : r.items); }
  useEffect(() => { void cargar(); }, [monitoreo]);
  function cerrar() { setNuevo(false); setPaso(1); setCampos({}); setBase({}); }
  async function borrar(id:string){if(!window.confirm("¿Quitar este registro?"))return;await api.request(`/registros/`,{method:"DELETE"});await cargar()} async function guardar(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = Object.fromEntries(new FormData(e.currentTarget)); await api.request("/registros", { method: "POST", body: JSON.stringify({ ...d, especificaciones: campos }) }); cerrar(); await cargar(); }
  async function exportar() { const data = await api.download("/monitoreo/registros/exportar"); await window.flowSort.saveFile("flowsort-registros.xlsx", data); }
  const actual = plantillas.find(p => p.id === plantillaId);
  return <><header><div><h1>{monitoreo ? "Monitoreo" : "Registros"}</h1><span>{items.length} resultados</span></div><div className="actions"><input placeholder="Buscar cliente" value={buscar} onChange={e => setBuscar(e.target.value)} onKeyDown={e => e.key === "Enter" && void cargar()} />{monitoreo && <button onClick={exportar}>Exportar Excel</button>}<button onClick={() => { setNuevo(true); setPaso(1); }}>+ Nuevo registro</button></div></header><StatsStrip items={items} /><div className="dashboard-content"><section className="panel"><table><thead><tr><th>Cliente</th><th>Plantilla</th><th>Prioridad</th><th>Estado</th><th>Fecha</th><th></th></tr></thead><tbody>{items.map(r => <tr key={r.id}><td>{r.nombreCliente}<small>{r.contacto}</small></td><td>{r.plantilla.nombre}</td><td><span className={`badge ${r.prioridad}`}>{r.prioridad.replace("_", " ")}</span></td><td>{r.estado.replace("_", " ")}</td><td>{new Date(r.fechaRegistro).toLocaleString()}</td></tr>)}</tbody></table></section><QuickInsights items={items} /></div>
    {nuevo && <div className="overlay"><form className="modal record-wizard" onSubmit={guardar}><div className="wizard-head"><div><small>PASO {paso} DE 2</small><h2>{paso === 1 ? "Cuéntanos lo básico" : "Completa los detalles"}</h2><p>{paso === 1 ? "Solo lo esencial para empezar." : `Campos de ${actual?.nombre ?? "tu plantilla"}.`}</p></div><button type="button" className="close-wizard" onClick={cerrar}>×</button></div><div className="wizard-progress"><i className={paso >= 1 ? "done" : ""} /><i className={paso >= 2 ? "done" : ""} /></div>{paso === 1 ? <div className="wizard-fields"><label>Nombre del cliente<input name="nombreCliente" autoFocus placeholder="Ej. María González" required /></label><label>Contacto <span className="optional">Opcional</span><input name="contacto" placeholder="Teléfono o email" /></label><label>¿Qué tipo de registro es?<select name="plantillaId" required value={plantillaId} onChange={e => { setPlantillaId(e.target.value); setCampos({}); }}>{plantillas.map(p => <option value={p.id} key={p.id}>{p.nombre}</option>)}</select></label><div className="row"><label>Prioridad<select name="prioridad"><option value="PREDETERMINADA">Normal</option><option value="BAJA">Baja</option><option value="ALTA">Alta</option><option value="SUPER_ALTA">Urgente</option></select></label><label>Estado<select name="estado"><option value="PENDIENTE">Pendiente</option><option value="EN_PROCESO">En proceso</option><option value="COMPLETADO">Completado</option></select></label></div></div> : <><input type="hidden" name="nombreCliente" value={base.nombreCliente??""}/><input type="hidden" name="contacto" value={base.contacto??""}/><input type="hidden" name="plantillaId" value={base.plantillaId??plantillaId}/><input type="hidden" name="prioridad" value={base.prioridad??"PREDETERMINADA"}/><input type="hidden" name="estado" value={base.estado??"PENDIENTE"}/><div className="wizard-fields"><DynamicFields campos={actual?.campos ?? []} valores={campos} onChange={setCampos} /></div></>}<div className="wizard-actions">{paso === 2 && <button type="button" className="secondary" onClick={() => setPaso(1)}>Atrás</button>}<button type="button" className="secondary" onClick={cerrar}>Cancelar</button>{paso === 1 ? <button type="button" onClick={(e) => { const d=Object.fromEntries(new FormData((e.currentTarget as HTMLButtonElement).form!)); setBase(d as Record<string,string>); setPaso(2); }}>Siguiente <span>→</span></button> : <button>Guardar registro <span>✓</span></button>}</div></form></div>}
  </>;
}
