import React from 'react';
import {Image,Pressable,ScrollView,Switch,Text,TextInput,View} from 'react-native';
import type {CampoPlantilla,Plantilla,Prioridad,Registro,Sesion} from '@flowsort/shared';
import {C,s} from './theme';

export function Brand({sesion}:{sesion:Sesion}){return <View style={[s.row,{padding:14,backgroundColor:C.nav,borderBottomWidth:1,borderColor:C.border}]}>{sesion.empresa.logoUrl?<Image source={{uri:sesion.empresa.logoUrl}} style={{width:38,height:38,borderRadius:9}}/>:<Image source={require('../assets/flowsort-logo.png')} resizeMode="contain" style={{width:52,height:38}}/>}<View><Text style={{color:C.text,fontSize:17,fontWeight:'800'}}>{sesion.empresa.nombre}</Text><Text style={s.subtitle}>FlowSort · {sesion.usuario.nombre}</Text></View></View>}

const PC:Record<Prioridad,string>={BAJA:C.low,PREDETERMINADA:C.aqua,ALTA:C.warn,SUPER_ALTA:C.danger};
export function Badge({value}:{value:Prioridad}){return <View style={{backgroundColor:PC[value]+'25',borderColor:PC[value],borderWidth:1,borderRadius:99,paddingHorizontal:9,paddingVertical:4}}><Text style={{color:PC[value],fontSize:11,fontWeight:'800'}}>{value.replace('_',' ')}</Text></View>}
export type RegistroVista=Registro&{plantilla?:Plantilla|{id:string;nombre:string;campos?:CampoPlantilla[]}};
export function RegistroCard({item,onPress,selected}:{item:RegistroVista;onPress:()=>void;selected?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={`Registro de ${item.nombreCliente}`} onPress={onPress} style={[s.card,selected&&{borderColor:C.active,borderWidth:2}]}><View style={s.between}><Text numberOfLines={1} style={{color:C.text,fontWeight:'800',fontSize:16,flex:1}}>{item.nombreCliente}</Text><Badge value={item.prioridad}/></View><Text style={[s.muted,{marginTop:6}]}>{item.plantilla?.nombre??'Plantilla'} · {new Date(item.fechaRegistro).toLocaleDateString()}</Text></Pressable>}
export function Detail({item,onEdit}:{item:RegistroVista|null;onEdit?:()=>void}){if(!item)return <View style={[s.card,{alignItems:'center',paddingVertical:40}]}><Text style={s.muted}>Seleccionar registro</Text></View>;return <ScrollView contentContainerStyle={s.card}><View style={s.between}><Text style={s.title}>{item.nombreCliente}</Text><Badge value={item.prioridad}/></View><Text style={[s.muted,{marginTop:5}]}>{item.contacto||'Sin contacto'}</Text><View style={s.divider}/><Text style={s.label}>Plantilla</Text><Text style={s.muted}>{item.plantilla?.nombre}</Text><Text style={[s.label,{marginTop:14}]}>Estado</Text><Text style={s.muted}>{item.estado.replace('_',' ')}</Text>{Object.entries(item.especificaciones).map(([k,v])=><View key={k} style={{marginTop:14}}><Text style={s.label}>{k}</Text><Text style={s.muted}>{typeof v==='boolean'?(v?'Sí':'No'):String(v??'')}</Text></View>)}{onEdit&&<Pressable onPress={onEdit} accessibilityRole="button" style={[s.button,{marginTop:20}]}><Text style={s.buttonText}>Editar registro</Text></Pressable>}</ScrollView>}
export function Choice<T extends string>({values,value,onChange,label}:{values:readonly T[];value:T;onChange:(v:T)=>void;label:string}){return <View style={{marginBottom:12}}><Text style={s.label}>{label}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{values.map(v=><Pressable key={v} onPress={()=>onChange(v)} style={[s.secondary,s.button,{minHeight:44},value===v&&{backgroundColor:C.aqua}]}><Text style={[s.secondaryText,value===v&&{color:C.base}]}>{v.replace('_',' ')}</Text></Pressable>)}</ScrollView></View>}
export function DynamicFields({campos,values,onChange}:{campos:CampoPlantilla[];values:Record<string,unknown>;onChange:(v:Record<string,unknown>)=>void}){return <>{campos.map(c=>{const set=(v:unknown)=>onChange({...values,[c.id]:v});if(c.tipo==='checkbox')return <View key={c.id} style={[s.between,{minHeight:48,marginBottom:10}]}><Text style={s.label}>{c.etiqueta}{c.requerido?' *':''}</Text><Switch accessibilityLabel={c.etiqueta} value={Boolean(values[c.id])} onValueChange={set} trackColor={{true:C.aqua}}/></View>;if(c.tipo==='select')return <Choice key={c.id} label={`${c.etiqueta}${c.requerido?' *':''}`} values={c.opciones??[]} value={String(values[c.id]??'') as never} onChange={set}/>;return <View key={c.id}><Text style={s.label}>{c.etiqueta}{c.requerido?' *':''}</Text><TextInput accessibilityLabel={c.etiqueta} placeholder={c.placeholder??c.etiqueta} placeholderTextColor={C.muted} value={String(values[c.id]??'')} onChangeText={v=>set(c.tipo==='numero'?(v===''?'':Number(v)):v)} keyboardType={c.tipo==='numero'?'numeric':c.tipo==='telefono'?'phone-pad':c.tipo==='email'?'email-address':'default'} multiline={c.tipo==='textarea'} style={[s.input,c.tipo==='textarea'&&s.textarea]}/></View>})}</>}
